- params:
    git:
      repoName: python-fb-ex
      branches:
        - main
    scan:
      projects:
        - workingDirs:
          - "Projects/python-fb-example/requirements/"
        - pipRequirementsFile: requirements.txt
        
